apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-apache
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: nginx-apache
